# Generated by Django 4.0.3 on 2022-03-27 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0002_remove_servicetag_product_invoice_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='order_fulfilled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoiceproduct',
            name='price_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='invoiceservice',
            name='price_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
