# Generated by Django 4.0.3 on 2022-03-27 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0003_invoice_order_fulfilled_invoiceproduct_price_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='full_address',
        ),
        migrations.AddField(
            model_name='vendor',
            name='state_province',
            field=models.CharField(blank=True, help_text='State/Province (if applicable)', max_length=1024, null=True),
        ),
    ]
