# Generated by Django 4.0.3 on 2022-03-27 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0004_remove_vendor_full_address_vendor_state_province'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='state_province',
            new_name='state_or_province',
        ),
    ]
