# Generated by Django 4.0.3 on 2022-03-27 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0005_rename_state_province_vendor_state_or_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttag',
            name='product',
        ),
        migrations.RemoveField(
            model_name='servicetag',
            name='service',
        ),
        migrations.AddField(
            model_name='productlisting',
            name='tags',
            field=models.ManyToManyField(to='storeApp.producttag'),
        ),
        migrations.AddField(
            model_name='servicelisting',
            name='tags',
            field=models.ManyToManyField(to='storeApp.servicetag'),
        ),
    ]
