# Generated by Django 4.0.3 on 2022-03-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0007_rename_quantityavailable_productlisting_quantity_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlisting',
            name='tags',
            field=models.ManyToManyField(blank=True, to='storeApp.producttag'),
        ),
        migrations.AlterField(
            model_name='servicelisting',
            name='tags',
            field=models.ManyToManyField(blank=True, to='storeApp.servicetag'),
        ),
    ]
