# Generated by Django 4.0.3 on 2022-03-30 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0009_alter_vendor_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productlisting',
            options={'permissions': (('can_set_active', 'Set product as active'),)},
        ),
    ]
