# Generated by Django 4.0.3 on 2022-03-31 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0012_alter_servicelisting_imageurl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='vendor',
        ),
        migrations.AddField(
            model_name='invoice',
            name='order_canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='order_shipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoiceproduct',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='storeApp.vendor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceservice',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='storeApp.vendor'),
            preserve_default=False,
        ),
    ]
