# Generated by Django 4.0.3 on 2022-03-31 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0014_remove_invoice_order_canceled_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceproduct',
            old_name='price_paid',
            new_name='unit_price',
        ),
        migrations.RemoveField(
            model_name='invoiceproduct',
            name='is_canceled',
        ),
        migrations.RemoveField(
            model_name='invoiceproduct',
            name='is_shipped',
        ),
        migrations.RemoveField(
            model_name='invoiceservice',
            name='is_canceled',
        ),
        migrations.RemoveField(
            model_name='invoiceservice',
            name='is_complete',
        ),
        migrations.AddField(
            model_name='invoiceproduct',
            name='quantity_ordered',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7),
        ),
    ]
