# Generated by Django 4.0.3 on 2022-04-01 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0015_rename_price_paid_invoiceproduct_unit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceproduct',
            name='total_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
