# Generated by Django 4.0.3 on 2022-04-01 00:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0016_invoiceproduct_total_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceproduct',
            name='quantity_ordered',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
