# Generated by Django 4.0.3 on 2022-04-01 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0017_alter_invoiceproduct_quantity_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceproduct',
            name='total_payment',
        ),
    ]
