# Generated by Django 4.0.3 on 2022-04-01 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0018_remove_invoiceproduct_total_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
