# Generated by Django 4.0.3 on 2022-04-01 01:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0019_invoice_total_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceproduct',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for this particular service', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoiceservice',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for this particular service', primary_key=True, serialize=False),
        ),
    ]
