# Generated by Django 4.0.3 on 2022-04-05 16:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storeApp', '0021_invoiceproduct_status_invoiceservice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceproduct',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for this product listing', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoiceproduct',
            name='status',
            field=models.CharField(blank=True, choices=[('or', 'Order Received'), ('cl', 'Canceled'), ('sh', 'Shipped')], default='or', help_text='Order Status', max_length=2),
        ),
        migrations.AlterField(
            model_name='invoiceproduct',
            name='vendor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='storeApp.vendor'),
        ),
        migrations.AlterField(
            model_name='invoiceservice',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for this service listing', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoiceservice',
            name='status',
            field=models.CharField(blank=True, choices=[('sc', 'Scheduled'), ('cl', 'Canceled'), ('cm', 'Completed')], default='sc', help_text='Order Status', max_length=2),
        ),
        migrations.AlterField(
            model_name='invoiceservice',
            name='vendor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='storeApp.vendor'),
        ),
        migrations.CreateModel(
            name='CartService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for this product in cart', primary_key=True, serialize=False)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='storeApp.productlisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for this product in cart', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(9999)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='storeApp.productlisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
