# Generated by Django 4.0.3 on 2022-04-05 18:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0022_alter_invoiceproduct_id_alter_invoiceproduct_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartservice',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for this service in cart', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cartservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='storeApp.servicelisting'),
        ),
    ]
