# Generated by Django 4.0.3 on 2022-04-05 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storeApp', '0023_alter_cartservice_id_alter_cartservice_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproduct',
            old_name='user',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='cartservice',
            old_name='user',
            new_name='cart',
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text="Unique ID for this user's cart", primary_key=True, serialize=False)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
