# Generated by Django 4.0.3 on 2022-04-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0026_rename_vendor_name_vendor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='logoURL',
            field=models.URLField(default='https://picsum.photos/400/300', help_text='Enter image URL'),
        ),
    ]
