# Generated by Django 4.0.3 on 2022-04-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0027_vendor_logourl'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='description',
            field=models.TextField(default='This is a sample vendor description'),
            preserve_default=False,
        ),
    ]
