# Generated by Django 4.0.3 on 2022-04-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0028_vendor_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttag',
            options={'ordering': ['viewcount']},
        ),
        migrations.AlterModelOptions(
            name='servicetag',
            options={'ordering': ['viewcount']},
        ),
        migrations.AddField(
            model_name='producttag',
            name='viewcount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicetag',
            name='viewcount',
            field=models.IntegerField(default=0),
        ),
    ]
